/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import NapakalakiGame.Player;

/**
 *
 * @author Cervi
 */
public class BadConsequenceView extends javax.swing.JPanel {
    
    BadConsequence badConsequenceModel;
    
    public void setBadConsequence(BadConsequence bc){
        badConsequenceModel=bc;
        if(bc.getLevels()==Player.MAXLEVEL && bc.getNVisibleTreasures()==BadConsequence.MAXTREASURES && bc.getNHiddenTreasures()==BadConsequence.MAXTREASURES ){
            lText.setText(bc.getText());
            repaint();
        }
        else{
            //lVisible.setText(String.valueOf(bc.getNVisibleTreasures()));
            //lHidden.setText(String.valueOf(bc.getNHiddenTreasures()));
//            lLevels.setText(String.valueOf(bc.getLevels()));
//            if(bc.getSpecificVisibleTreasures()!=null)
//                lVisible.setText(bc.getSpecificVisibleTreasures().toString());
//            if(bc.getSpecificHiddenTreasures()!=null)
//                lHidden.setText(bc.getSpecificHiddenTreasures().toString());
            lText.setText(bc.getText());
            repaint();
        }
        repaint();
    }

    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        lText.setText("jLabel2");

        jLabel2.setText("BADCONSEQUENCE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lText, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lText, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lText;
    // End of variables declaration//GEN-END:variables
}
