/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;

/**
 *
 * @author Usuario
 */
public class NapakalakiView extends javax.swing.JFrame {

    Napakalaki napakalakiModel;
    
    
    
    public void setNapakalaki(Napakalaki nModel){
        this.napakalakiModel=nModel;
        if(napakalakiModel.getCurrentPlayer()!=null)
             playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        if(napakalakiModel.getCurrentMonster()!=null)
            monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        
        monsterView1.setVisible(false);
        bMeet.setEnabled(true);
        bNextTurn.setEnabled(false);
        repaint();
        revalidate();
    }
    
    public NapakalakiView() {
        initComponents();
        bCombat.setEnabled(false);
        bNextTurn.setEnabled(false);
        LCombatResult.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        playerView1 = new GUI.PlayerView();
        monsterView1 = new GUI.MonsterView();
        bMeet = new javax.swing.JButton();
        bCombat = new javax.swing.JButton();
        bNextTurn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LCombatResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 39, 0);
        getContentPane().add(playerView1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 95);
        getContentPane().add(monsterView1, gridBagConstraints);

        bMeet.setText("Meet the monster");
        bMeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMeetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 25, 0, 0);
        getContentPane().add(bMeet, gridBagConstraints);

        bCombat.setText("Combat");
        bCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCombatActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 6, 0, 0);
        getContentPane().add(bCombat, gridBagConstraints);

        bNextTurn.setText("Next turn");
        bNextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNextTurnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 10, 0, 0);
        getContentPane().add(bNextTurn, gridBagConstraints);

        jLabel1.setText("Combat Result:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(118, 10, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        LCombatResult.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(118, 18, 0, 0);
        getContentPane().add(LCombatResult, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bMeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMeetActionPerformed
        monsterView1.setVisible(true);
        bCombat.setEnabled(true);
        bMeet.setEnabled(false);
        bNextTurn.setEnabled(false);
        playerView1.bDiscardAll.setEnabled(false);
        playerView1.bMakeVisible.setEnabled(false);
        playerView1.bSteal.setEnabled(false);
        playerView1.bDiscard.setEnabled(false);
    }//GEN-LAST:event_bMeetActionPerformed

    private void bCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCombatActionPerformed
        CombatResult cr = napakalakiModel.developCombat();
        if(cr==CombatResult.WIN)    LCombatResult.setText("WIN");
        if(cr==CombatResult.LOSE)    LCombatResult.setText("LOSE");
        if(cr==CombatResult.LOSEANDCONVERT)    LCombatResult.setText("LOSE&CONVERT!!");
        if(cr==CombatResult.WINGAME){
            LCombatResult.setText("GANASTE");
            System.exit(0);
        } 
        playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        bCombat.setEnabled(false);
        bNextTurn.setEnabled(true);
        playerView1.bDiscardAll.setEnabled(true);
        playerView1.bMakeVisible.setEnabled(true);
        playerView1.bSteal.setEnabled(true);
        playerView1.bDiscard.setEnabled(true);
        
    }//GEN-LAST:event_bCombatActionPerformed

    private void bNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNextTurnActionPerformed
        if(napakalakiModel.nextTurn()){
            setNapakalaki(napakalakiModel);
            LCombatResult.setText("");
            playerView1.hidePending();
        }
        else{
            bMeet.setEnabled(false);
            bCombat.setEnabled(false);
            playerView1.showPending();
            
        }
    }//GEN-LAST:event_bNextTurnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCombatResult;
    private javax.swing.JButton bCombat;
    private javax.swing.JButton bMeet;
    private javax.swing.JButton bNextTurn;
    private javax.swing.JLabel jLabel1;
    private GUI.MonsterView monsterView1;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
