/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;

/**
 *
 * @author Cervi
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {

    BadConsequence pendingBadConsequenceModel;
    
    public void setPendingBad(BadConsequence pending){
        if(pending!=null){
            pendingBadConsequenceModel=pending;
            lNVisible.setText(String.valueOf(pending.getNVisibleTreasures()));
            lNHidden.setText(String.valueOf(pending.getNHiddenTreasures()));
            if(pending.getSpecificVisibleTreasures()!=null)
                lSpecificVisible.setText(pending.getSpecificVisibleTreasures().toString());
            else
                lSpecificVisible.setText("");
            if(pending.getSpecificHiddenTreasures()!=null)
                lSpecificHidden.setText(pending.getSpecificHiddenTreasures().toString());
            else
                lSpecificHidden.setText("");
        }
        else{
            lNVisible.setText("");
            lNHidden.setText("");
            lSpecificVisible.setText("");
            lSpecificHidden.setText("");
        }
        repaint();
    }
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lNVisible = new javax.swing.JLabel();
        lNHidden = new javax.swing.JLabel();
        lSpecificHidden = new javax.swing.JLabel();
        lSpecificVisible = new javax.swing.JLabel();

        jLabel1.setText("PendingBadConsequence");

        jLabel2.setText("nVisible:");

        jLabel3.setText("nHidden:");

        jLabel4.setText("specificHiddenTreasures:");

        jLabel5.setText("specificVisibleTreasures:");

        lNVisible.setText("jLabel6");

        lNHidden.setText("jLabel6");

        lSpecificHidden.setText("jLabel6");

        lSpecificVisible.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lNVisible)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lNHidden)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lSpecificHidden, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(lSpecificVisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lNVisible)
                    .addComponent(jLabel5)
                    .addComponent(lSpecificVisible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lNHidden)
                    .addComponent(jLabel4)
                    .addComponent(lSpecificHidden))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lNHidden;
    private javax.swing.JLabel lNVisible;
    private javax.swing.JLabel lSpecificHidden;
    private javax.swing.JLabel lSpecificVisible;
    // End of variables declaration//GEN-END:variables
}
